### ISSUE TITLE
Support .NetStandard >=2.0

### ISSUE THREAD

**Issue by johanskoldekrans** [EdCharbeneau/BlazorPro.Spinkit#1]
We are using this in a shared project and the shared project is .NetStandard 2.1. Everything explodes :-)

**Comment by EdCharbeneau** [comment]
Fixed, please report back if version 1.1.0 does not resolve your issue.

**Comment by johanskoldekrans** [comment]
@EdCharbeneau Sorry for not responding to this earlier. Works like a charm! :-)
