### ISSUE TITLE
Cannot build Xamarin IOS with 1.1.1

### ISSUE THREAD

**Issue by whann0205** [EdCharbeneau/BlazorPro.Spinkit#14]
Thanks for your attempts to solve the problem!
I have rerun the build process and changed the language to english for your convenience.
The error message:
The path '..\..\..\blazorpro.spinkit\1.1.1-pre\staticwebassets\spinkit.min.css' would result in a file outside of the app bundle and cannot be used.	AssetQueryApp.iOS	C:\Users\hann.HANN-EDV\.nuget\packages\blazorpro.spinkit\1.1.1-pre\staticwebassets\spinkit.min.css		
I am glad to hear that you will support .net6 maui. I will for sure upgrade to that plattform, since its
exactly the thing i wanted to do after i decided to use MBB. 
That all those things are either in preview or experimental does not stop me from using it, since
my project is small and i dont have to follow anyone´s policies in this matter.

**Comment by EdCharbeneau** [comment]
Prior to .NET 6 preview 4 (blazormaui). Razor Class Libraries like Spinkit are not supported. I haven't started testing preview 4 yet with Spinkit, however the Telerik UI for Blazor assemblies do work in that environment so it's pretty safe to assume that Spinkit does as well.

Thanks for bringing this to my attention, but I'm marking this as wontfix and placing my efforts on .NET 6.

You can find the raw assets for sinkit in HTML/CSS format if you would like to implement them directly in your apps. https://tobiasahlin.com/spinkit/

-Ed

**Comment by whann0205** [comment]
OK.
But just for the recods MBB supports RCL.
See:
https://github.com/MicrosoftDocs/mobile-blazor-bindings/blob/master/mobile-blazor-bindings/walkthroughs/shared-web-ui.md
