### ISSUE TITLE
spinner replaces page content.

### ISSUE THREAD

**Issue by figuerres** [EdCharbeneau/BlazorPro.Spinkit#17]
the current spinner breaks the page, if it does not render the rest of the controls on the page then they lose their state and this make this non-usable.
for example i have a data grid with multiple filter options for data columns. if the component is not rendered then the settings the user entered are lost.
what about a spinner that just makes an html block that overlays on top of the other page content so that the busy state just changes the css used so that it can hide/show the spinner but not block the render of other page controls?

**Comment by EdCharbeneau** [comment]
Please provide a sample. There is likely something other than the spinner component causing this. There's not really a lot of logic in the spinner component.
