### ISSUE TITLE
Circle loader displaying flickering boxes

### ISSUE THREAD

**Issue by jthawkins96** [EdCharbeneau/BlazorPro.Spinkit#6]
Hi,

When we define a size on the Circle loader it's causing these squares to occasionally flicker in and out. I tested it without defining a size and it works as expected. I also tested a couple other loaders and those were working as expected as well, both with and without a defined size. 
![circle-loader-flicker](https://user-images.githubusercontent.com/22065544/82238612-9613fd00-9905-11ea-9ea8-2c81a7e45931.png)

**Comment by EdCharbeneau** [comment]
Sorry, for some reason I didn't receive a notification when the issue was posted. I will investigate.

**Comment by EdCharbeneau** [comment]
Thanks for reporting the issue. The issue is now tracked on the CSS repo where the styles maintained. It appears to be a chrome issue when the spinner size is small. https://github.com/tobiasahlin/SpinKit/issues/136
